# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dist_v5.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1133, 743)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_button.setGeometry(QtCore.QRect(50, 110, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.open_button.setFont(font)
        self.open_button.setObjectName("open_button")
        self.det_button = QtWidgets.QPushButton(self.centralwidget)
        self.det_button.setGeometry(QtCore.QRect(700, 110, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.det_button.setFont(font)
        self.det_button.setObjectName("det_button")
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_button.setGeometry(QtCore.QRect(350, 110, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.play_button.setFont(font)
        self.play_button.setObjectName("play_button")
        self.video_label = QtWidgets.QLabel(self.centralwidget)
        self.video_label.setGeometry(QtCore.QRect(50, 220, 1011, 481))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.video_label.setFont(font)
        self.video_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.video_label.setStyleSheet("border: 2px solid black; border-radius: 5px; font-weight: bold;")
        self.video_label.setScaledContents(False)
        self.video_label.setAlignment(QtCore.Qt.AlignCenter)
        self.video_label.setIndent(-1)
        self.video_label.setObjectName("video_label")
        self.det_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.det_label_2.setGeometry(QtCore.QRect(350, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.det_label_2.setFont(font)
        self.det_label_2.setObjectName("det_label_2")
        self.det_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.det_label_3.setGeometry(QtCore.QRect(700, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.det_label_3.setFont(font)
        self.det_label_3.setObjectName("det_label_3")
        self.det_label_4 = QtWidgets.QLabel(self.centralwidget)
        self.det_label_4.setGeometry(QtCore.QRect(460, 10, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.det_label_4.setFont(font)
        self.det_label_4.setObjectName("det_label_4")
        self.obj_label = QtWidgets.QLCDNumber(self.centralwidget)
        self.obj_label.setGeometry(QtCore.QRect(550, 160, 131, 41))
        self.obj_label.setObjectName("obj_label")
        self.det_label = QtWidgets.QLCDNumber(self.centralwidget)
        self.det_label.setGeometry(QtCore.QRect(900, 160, 131, 41))
        self.det_label.setObjectName("det_label")
        self.det_label_5 = QtWidgets.QLabel(self.centralwidget)
        self.det_label_5.setGeometry(QtCore.QRect(350, 160, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.det_label_5.setFont(font)
        self.det_label_5.setObjectName("det_label_5")
        self.det_label_6 = QtWidgets.QLabel(self.centralwidget)
        self.det_label_6.setGeometry(QtCore.QRect(700, 160, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.det_label_6.setFont(font)
        self.det_label_6.setObjectName("det_label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.open_button.clicked.connect(MainWindow.open_video)
        self.det_button.clicked.connect(MainWindow.toggle_detback)
        self.play_button.clicked.connect(MainWindow.toggle_playback)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_button.setText(_translate("MainWindow", " Load video"))
        self.det_button.setText(_translate("MainWindow", "Start detecting"))
        self.play_button.setText(_translate("MainWindow", "Start tracking"))
        self.video_label.setText(_translate("MainWindow", "Please open the video."))
        self.det_label_2.setText(_translate("MainWindow", "tracking info"))
        self.det_label_3.setText(_translate("MainWindow", "detection info "))
        self.det_label_4.setText(_translate("MainWindow", "Surveillance Video"))
        self.det_label_5.setText(_translate("MainWindow", "Number of tracking"))
        self.det_label_6.setText(_translate("MainWindow", "Number of detecting"))
